### ISSUE TITLE
Run with preact 8.4.2 tries to load preact/test-utils

### ISSUE THREAD

**Issue by kontrollanten** [preactjs/enzyme-adapter-preact-pure#35] opened 2019-04-15 07:45 UTC
Upgrading enzyme-adapter-preact-pure to v1.12.0 gives this error:

```
Error: Cannot find module 'preact/test-utils' from '/home/circleci/project/node_modules/enzyme-adapter-preact-pure/build/src'
```

I'm using preact 8.4.2, it seems like enzyme-adapter-preact-pure thinks I'm using preact 10.

https://github.com/kontrollanten/preact-leaflet/pull/45

**Comment by robertknight** [comment] 2019-04-15 08:18
Ah, this is happening when Browserify bundles your modules for use in Karma ([CircleCI output](https://circleci.com/gh/kontrollanten/preact-leaflet/103?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)). The problem is that Browserify sees `require('preact/test-utils')` and doesn't know whether the runtime check around it will pass or not, so it has to assume it will be needed.

Hmm ... that's annoying. A workaround is to use Browserify's `ignore` option ([see README](https://github.com/browserify/browserify)) to just omit that module.

**Comment by kilgarenone** [comment] 2019-09-03 05:24
How to do this for Webpack?

**Comment by robertknight** [comment] 2021-01-10 23:31
There will soon be a new release of the adapter (v3.0.0) which removes support for Preact v8 in order to simplify future maintenance. See https://github.com/preactjs/enzyme-adapter-preact-pure/issues/117 for more details. Users of Preact v8 can continue to use the previous version of the adapter or update their libraries/apps to use Preact v10.

As a result, I'm going to close this issue and ask anyone affected to use one of the workarounds suggested here.

**Closed by robertknight** 2021-01-10 23:31 UTC
Labels: bug
