### ISSUE TITLE
Shallow rendering snapshot includes full html

### ISSUE THREAD

**Issue by MrHus** [preactjs/enzyme-adapter-preact-pure#13] opened 2019-03-20 19:31 UTC
First of all thank you for working on this enzyme adapter it has been very useful to me.

But I think I have discovered a bug: I have a component called `Detail` which renders a `Title` component like so:

```
<Title animal={data.animal} />
```

In the snapshot the following appears:

```
<Title
  animal={
    Object {
      "name": "Hank",
    }
  }
>
  <header
    className="header"
  >
    <h1>
      Hank
  </header>
</Title>
```
This is unexpected, since the `h1` is part of the `Title` which I'm not shallow rendering.

The test:

```js
/* @flow @jsx h */
import { h } from 'preact';
import { shallow } from 'enzyme';

import Detail from './Detail';

describe('Detail component', () => {
  let detail;

  describe('ui', () => {
    it('should know how to render occasions when everything goes right', () => {
      const detail = shallow(<Detail />);

      expect(detail).toMatchSnapshot();
    });
  });
});
```

The Detail component itself:

```js
class Detail extends Component<Props, State> {
  render() {
    return (<Title animal={{name: "Hank"}} />);
   }
}
```

**Comment by robertknight** [comment] 2019-03-21 12:20
Can you provide some additional details:

- What is the output of `console.log(detail.debug())` above the line where you call `expect(detail).toMatchSnapshot()`?
- How is the serialization of the `detail` wrapper object returned by the `shallow(...)` call into the snapshot format configured? Are you using something like [enzyme-to-json](https://medium.com/codeclan/testing-react-with-jest-and-enzyme-20505fec4675)?
- Which version of Preact are you using?
- Are you using preact/compat or just preact directly?

**Comment by MrHus** [comment] 2019-03-22 07:17
The detail.debug output:

```
console.log src/detail/components/Detail/Detail.spec.js:41
    <Title animal={{...}}>
      <header className="header">
        <h1>
          Hank
        </h1>
      </header>
    </Title>
```

Preact versions:

"preact": "8.4.2",
"preact-compat": "3.18.4",

Serializers: `"snapshotSerializers": ["enzyme-to-json/serializer"],`

**Comment by robertknight** [comment] 2019-03-22 10:58
Thanks for the info. It looks like the problem is unrelated to the enzyme-to-json serializer if it shows up in the `debug()` output. I wasn't able to reproduce this yesterday with a test case in this project's tests, but that was using just "preact", not "preact-compat", so it is possible that is related.

**Comment by robertknight** [comment] 2019-03-23 10:07
One possible explanation for the behaviour here might be if two copies of the Preact library are being used. Shallow rendering works by hooking into VDOM node creation using Preact's `options.vnode`. If the Enzyme adapter is using a different copy of Preact than your tests then its shallow-rendering hook will not be applied.

I can't immediately see why multiple copies of the library would be used, but it would be worth checking the `node_modules/` tree to see if this is the case.

**Comment by robertknight** [comment] 2019-04-29 00:07
In order to address this issue it would be helpful to get a complete test case (eg. on https://codesandbox.io or a Git repo) which reproduces the issue. One other thing to note is that this library has been tested more extensively with the upcoming Preact 10 release (and preact/compat) than Preact 8, so it might be worth testing with that as well.

**Comment by robertknight** [comment] 2019-06-17 15:35
I'm going to close this issue as unable to reproduce at present. If you provide a minimal test case I can re-open.

**Closed by robertknight** 2019-06-17 15:35 UTC
Labels: question
