### ISSUE TITLE
Preact useState/useEffect Value Problem

### ISSUE THREAD

**Issue by Jitsusama** [preactjs/enzyme-adapter-preact-pure#71] opened 2019-08-30 14:58 UTC
Hello;

I've been trying (unsuccessfully) to test a component that performs asynchronous fetching of data as an effect in order to update state, which should get reflected upon the next render. What happens is that when I query the mounted component via Enzyme, I only see the initial state's value, and not the value that the state should be finally set to. I've tried adding `setTimeout`s in my test code, wrapping things in `act`, but nothing seems to work.

I've boiled this down into the simplest code that can replicate my issue. For reference, I'm utilizing jest v24.9.0, preact v10.0.0-rc.1, enzyme v3.10.0 and enzyme-adapter-preact-pure v2.0.2. Below is a simplified synchronous and asynchronous example, as I've found that the same issue is happening to me in both scenarios:

```javascript
import {configure, mount} from 'enzyme';
import {PreactAdapter} from 'enzyme-adapter-preact-pure';
import {h} from 'preact';
import {useEffect, useState} from 'preact/hooks';

beforeAll(() => {
    configure({adapter: new PreactAdapter});
});

test('handles promised effect/state combo', () => {
    const wrapper = mount(<PromisedEffect/>);
    wrapper.update();

    console.debug(wrapper.html());
    expect(wrapper.find('p').text()).toEqual('goodbye');
});

function PromisedEffect() {
    let [value, setValue] = useState('hello');
    useEffect(() => {
        Promise.resolve('goodbye').then(v => setValue(v));
    });

    console.debug('Promised Render Value:', value);

    return <p>{value}</p>;
}

test('handles standard effect/state combo', () => {
    const wrapper = mount(<StandardEffect/>);
    wrapper.update();

    console.debug(wrapper.html());
    expect(wrapper.find('p').text()).toEqual('goodbye');
});

function StandardEffect() {
    let [value, setValue] = useState('hello');
    useEffect(() => {
        setValue('goodbye');
    });

    console.debug('Standard Render Value:', value);

    return <p>{value}</p>;
}
```

Running this via the Jest test runner gives the following output:

```text
 FAIL  src/effect.test.js
  × handles promised effect/state combo (33ms)
  × handles standard effect/state combo (8ms)

  ● handles promised effect/state combo

    expect(received).toEqual(expected) // deep equality

    Expected: "goodbye"
    Received: "hello"

      13 | 
      14 |     console.debug(wrapper.html());
    > 15 |     expect(wrapper.find('p').text()).toEqual('goodbye');
         |                                      ^
      16 | });
      17 | 
      18 | function PromisedEffect() {

      at Object.toEqual (src/effect.test.js:15:38)

  ● handles standard effect/state combo

    expect(received).toEqual(expected) // deep equality

    Expected: "goodbye"
    Received: "hello"

      32 | 
      33 |     console.debug(wrapper.html());
    > 34 |     expect(wrapper.find('p').text()).toEqual('goodbye');
         |                                      ^
      35 | });
      36 | 
      37 | function StandardEffect() {

      at Object.toEqual (src/effect.test.js:34:38)

  console.debug src/effect.test.js:24
    Promised Render Value: hello

  console.debug src/effect.test.js:14
    <p>hello</p>

  console.debug src/effect.test.js:24
    Promised Render Value: goodbye

  console.debug src/effect.test.js:43
    Standard Render Value: hello

  console.debug src/effect.test.js:33
    <p>hello</p>

Test Suites: 1 failed, 1 total
Tests:       2 failed, 2 total
Snapshots:   0 total
Time:        5.074s, estimated 7s
Ran all test suites matching /effect.test.js/i.
```

I've been banging my head on this for a while, and it doesn't seem to be specific to how I'm writing my test code, but then again, maybe I'm missing something.

**Comment by robertknight** [comment] 2019-08-30 17:02
The `PromisedEffect` example does not work because the promise is resolved asynchronously and does not run until after `mount()` has returned and after that test finishes. There is no way to make promises resolve synchronously in JS, so you need to somehow `await` the promise in your test and _then_ call `wrapper.update()` before making assertions.

Can you test if the `StandardEffect` example works in isolation, i.e. without running the `PromisedEffect` example in the same test run? I think that might have hit an issue that is resolved in the next Preact release to do with mixing state updates that happen outside of `act`/`mount` calls and state updates that happen inside `act`/`mount` calls.

**Comment by Jitsusama** [comment] 2019-08-30 17:38
@robertknight; thanks for your response!

Regarding asynchronicity in tests, I must admit that I'm a bit new to this in the world of JavaScript. I'm used to using Promises, but not so used to how to deal with some of these stranger edge cases, particularly when third party code is sitting between my code and my tests. Are you recommending that I somehow pass in a mock asynchronous call, that will trigger a function performing the expects when it's complete, and then utilize Jest's `done` callback in the expect performing function to signal when everything is all complete?

In regards to validation of `StandardEffect`, I want to make sure I understand your request. Are you wanting me to perform a manual validation that everything looks right if I actually run the code in a browser? I did manage to figure out a hack to get that scenario to work in test by the way, but I'm pretty sure it comes down to timing, and specifically requires the use of `setProps` (not `update`) after the timeout and might not work in all similar scenarios. Here's the hack:

```javascript
test('handles standard effect/state combo', () => {
    const wrapper = mount(<StandardEffect/>);

    return new Promise(resolve => setTimeout(resolve, 0)).then(() => {
        wrapper.setProps(wrapper.props());
        expect(wrapper.find('p').text()).toEqual('goodbye');
    })
});
```

I managed to hack around `PromisedEffect` in a simpler way, but I also verified that in my actual production code, I have to judiciously sprinkle a bunch of `setProps` around in strategic locations to get it to work. I've found that `update` isn't doing anything to help in this scenario. Here's the hack code that works in my simple example:

```javascript
test('handles promised effect/state combo', () => {
    const wrapper = mount(<PromisedEffect/>);
    return new Promise(resolve => setTimeout(resolve, 0)).then(() => {
        expect(wrapper.find('p').text()).toEqual('goodbye');
    });
});
```

**Comment by Jitsusama** [comment] 2019-08-30 18:08
FYI; I verified that both `PromisedEffect` and `StandardEffect` work as is without issue when rendered to a browser. Here's the code:

```javascript
import {h, render} from 'preact';
import {useEffect, useState} from 'preact/hooks';

function Index() {
    return <div><PromisedEffect/><StandardEffect/></div>
}
function PromisedEffect() {
    let [value, setValue] = useState('hello');
    useEffect(() => {
        Promise.resolve('goodbye').then(v => setValue(v));
    });
    return <p>{value}</p>;
}
function StandardEffect() {
    let [value, setValue] = useState('hello');
    useEffect(() => {
        setValue('goodbye');
    });
    return <p>{value}</p>;
}

render(<Index/>, document.body);
```

**Comment by Jitsusama** [comment] 2019-08-30 18:08
Wait, nevermind, they print `hello` :(

**Comment by robertknight** [comment] 2019-08-31 09:35
> Are you recommending that I somehow pass in a mock asynchronous call, that will trigger a function performing the expects when it's complete, and then utilize Jest's done callback in the expect performing function to signal when everything is all complete?

I would try to write the test in such a way that it doesn't depend too much on the details of how the component works internally. Supposing there is a component that, from a consumer's point of view, does this:

1. Component is rendered with some initial output and a network request is made
2. Some time later, the network request completes and the component updates

Then in your test you set up a fake network response, `mount` the component and check the initial output, then spin in a loop, up to some timeout, until the component updates and shows the data it fetched from the network.

In order to do the "spin in a loop" part, you can either use something like `setInterval` with a callback that resolves a Promise when a condition is met, or use a pre-built helper like [wait-for-expect](https://yarnpkg.com/en/package/wait-for-expect).

Unfortunately I don't have a completely self-contained example to hand, but [here is an example](https://github.com/hypothesis/lms/blob/100935b070fd6f125cfa4642f1b7289444b62cbb/lms/static/scripts/frontend_apps/components/test/BasicLtiLaunchApp-test.js#L108) of a test in a real application doing something conceptually similar, where a test mounts a component, waits for it to show certain output (a button) after an API call fails, simulate clicking the button, then waits for some different output to be shown after the API call is attempted again and completes.

> In regards to validation of StandardEffect, I want to make sure I understand your request. Are you wanting me to perform a manual validation that everything looks right if I actually run the code in a browser? 

Sorry, I wasn't clear enough. I meant to comment out the `PromisedEffect` test and run just the `StandardEffect` test on its own, but still in Jest as you were doing before. My hypothesis is that the `PromisedEffect` test is interfering with the `StandardEffect` test.

> FYI; I verified that both PromisedEffect and StandardEffect work as is without issue when rendered to a browser. Here's the code:

Yes, that's because the problem is a timing issue. In your tests you are checking whether the HTML updated before the async steps (in the `Promise.resolve().then` callback) have executed.

**Comment by Jitsusama** [comment] 2019-09-03 11:38
Thanks for the further comments @robertknight. Commenting out the `PromisedEffect` test allows me to take out the workaround in my `StandardEffect` code and it passes without issue:

```javascript
test('handles standard effect/state combo', () => {
    const wrapper = mount(<StandardEffect/>);
    expect(wrapper.find('p').text()).toEqual('goodbye');
});
```

I'll try your idea of having a loop. My test code definitely runs based upon cause and effect and does not rely on internal implementation details. The only thing I really touch is mocking out a downstream Promise based data retrieval service module so that I don't cause actual network traffic to occur. I'm currently performing a `result.then()` on that mock to determine when to run my expectations, but since the calling code also performs a `.then()` on the response of the mock, my timing still ends up being just slightly off I believe.

To clarify, is this the expectation with _ezyme-adapter-preact-pure_? That there is no way to ensure that promises have completed before performing a `.render()` on the wrapped component? Will I always have to manually perform a `.update()` on the wrapped component and hope my timing was right when the wrapped component (or some part of its hierarchy) performs an asynchronous action?

**Comment by Jitsusama** [comment] 2019-09-03 19:27
So; @robertknight, using _wait-for-expect_ worked great for my `PromisedEffect`, without any `.update()` or `.setProps({})` required. For my actual application code, I've found that I need to run `.setProps()` right after mounting, and then I utilize _wait-for-expect_, with a `.update()` call in its callback and that seems to work. If I switch that order, or move one call into the wrong place, it doesn't work. Not sure why I need to use `.setProps()` and `.update()` in my production code but not my simplified test code, but such is the way of things I guess.

If you're interested in digging further, I can give you my actual production code, there isn't anything proprietary in it. If you expect that this is the way things are and it's not worth digging into further, I'll understand.

**Comment by robertknight** [comment] 2019-10-03 07:39
I'm closing this issue as I think the discussion has been resolved.

**Closed by robertknight** 2019-10-03 07:39 UTC
