### ISSUE TITLE
Expected VDOM node to be a DOM node but got undefined - piocstyle/preact x beta 3

### ISSUE THREAD

**Issue by samueljseay** [preactjs/enzyme-adapter-preact-pure#61] opened 2019-07-05 03:51 UTC
When rendering components using `mount` I get the error:

`Expected VDOM node to be a DOM node but got undefined`

After some debugging I noticed the offending components do not have an `__e` at top level which is required by https://github.com/preactjs/enzyme-adapter-preact-pure/blob/master/src/preact10-internals.ts#L87, 

rather they have only a `__p` (parent?) property.

Example console dump of a picostyle styled `i` tag:

```
{ __p:
         { type: 'i',
           props:
            { size: 20,
              iconName: 'image',
              styles: [Object],
              class: 'p1',
              children: [Circular] },
           key: undefined,
           ref: undefined,
           __k: [ [Circular] ],
           __p:
            { type: [Function],
              props: [Object],
              key: undefined,
              ref: undefined,
              __k: [Array],
              __p: [Object],
              __b: 5,
              __e: HTMLElement {},
              l: null,
              __c: [y],
              constructor: undefined },
           __b: 6,
           __e: HTMLElement {},
           l: null,
           __c: null,
           constructor: undefined },
        __b: 7 }
```
I use picostyle to render components but it still defers to Preact's `h`, so I'm not sure if this is a picostyle issue or a compatibility issue in enzyme-adapter-preact-pure. My lack of knowledge around how Preact's rendering does/should work means I'm quite stumped here, is it valid for only a `__p` to exist?

EDIT: also this is using latest version of adapter. 2.0.0

**Comment by robertknight** [comment] 2019-07-05 06:12
Hello @samueljseay, I created a [quick test on CodeSandbox](https://codesandbox.io/s/preact-picostyle-enzyme-qhygb) using Preact 10, picostyle and Enzyme but was unable to reproduce the issue.

Can you please create a _minimal_ project that reproduces the problem, either as a Code Sandbox, GitHub repo or Gist.

**Comment by samueljseay** [comment] 2019-07-05 21:00
@robertknight I was able to reproduce it with your example, just mount the picostyle node directly: https://codesandbox.io/s/preact-picostyle-enzyme-6x5kl

**Comment by robertknight** [comment] 2019-07-06 09:48
After some debugging, it looks like picostyle is subtly broken with Preact 10.

When the wrapper component is rendered, it is called with two arguments: `props` and `context`, where `context` defaults to an empty object (`{}`). The place where Preact calls the picostyle component's render function is here: https://github.com/preactjs/preact/blob/984f18dc20cc7a2ec3cd30f29c25aac0c53dbca0/src/diff/index.js#L311

Picostyle however expects the render function to be called with the second argument being the _children_ of the component, not the context. This should be an element, string or array. See https://github.com/morishitter/picostyle/blob/9f4053f806adbedbd7ee916e42f8153fbaccd948/src/index.js#L57

The result is that an invalid vnode gets generated which later trips up the Enzyme adapter, and probably breaks other things as well.

The error can be reproduced without Picostyle using:

```js
import { h } from "preact";
import { configure, mount } from "enzyme";
import { Adapter } from "enzyme-adapter-preact-pure";

function App() {
  return h('div', {}, {} /* Not a valid `children` argument */);
}

configure({ adapter: new Adapter() });

mount(<App />);
```

The `preact/debug` package could potentially catch this error when `h` is called and warn the developer about it. In the meantime, since the problem is not an issue with the adapter itself, I'm going to close this issue. If you could report it upstream to the Picostyle author, that would be appreciated.

**Closed by robertknight** 2019-07-06 09:48 UTC
Labels: needs more info

**Comment by marvinhagemeister** [comment] 2019-07-06 15:20
Yeah that function signature in `picostyle` is wrong. The second argument has never been `children`, even for other libraries as far as I can tell.

**Comment by samueljseay** [comment] 2019-07-06 21:08
Thanks all! I will raise this on picostyle!
